"""add_area_items_table

Revision ID: 0b7b6166424d
Revises: ccc7ffefbf89
Create Date: 2026-05-17 21:51:51.354891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7b6166424d'
down_revision: Union[str, Sequence[str], None] = 'ccc7ffefbf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('area_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_items_id'))

    op.drop_table('area_items')
    # ### end Alembic commands ###
