"""add_price_unit_to_accommodation_types

Revision ID: 312ca13b4ab5
Revises: 5d4dcd123d82
Create Date: 2026-05-16 13:48:44.304691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312ca13b4ab5'
down_revision: Union[str, Sequence[str], None] = '5d4dcd123d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodationTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priceUnit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodationTypes', schema=None) as batch_op:
        batch_op.drop_column('priceUnit')

    # ### end Alembic commands ###
