"""add_about_slider_item

Revision ID: 551c70535658
Revises: 0d8f3e2a1b4c
Create Date: 2026-05-10 15:01:37.533547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551c70535658'
down_revision: Union[str, Sequence[str], None] = '0d8f3e2a1b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('about_slider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_about_slider_id'), ['id'], unique=False)

    with op.batch_alter_table('price_list_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_list_data_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_list_data_id'), ['id'], unique=False)

    with op.batch_alter_table('about_slider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_about_slider_id'))

    op.drop_table('about_slider')
    # ### end Alembic commands ###
