"""add_rental_items

Revision ID: 594302bcaea1
Revises: 75077cd7c6d2
Create Date: 2026-05-05 09:30:31.004243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594302bcaea1'
down_revision: Union[str, Sequence[str], None] = '75077cd7c6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('badge', sa.String(length=100), nullable=True),
    sa.Column('badgeColor', sa.String(length=100), nullable=True),
    sa.Column('eyebrow', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_items_id'))

    op.drop_table('rental_items')
    # ### end Alembic commands ###
