"""add_admin_emails_table

Revision ID: 69a6a18bfe32
Revises: d63c31eca198
Create Date: 2026-05-17 20:20:14.483979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a6a18bfe32'
down_revision: Union[str, Sequence[str], None] = 'd63c31eca198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_emails_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_emails_id'))

    op.drop_table('admin_emails')
    # ### end Alembic commands ###
