"""add_accommodations_and_link_bookings

Revision ID: 75077cd7c6d2
Revises: 7c3daf2cd7b2
Create Date: 2026-05-04 23:14:29.702517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75077cd7c6d2'
down_revision: Union[str, Sequence[str], None] = '7c3daf2cd7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['typeId'], ['accommodationTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodations_id'), ['id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodationId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_accommodation', 'accommodations', ['accommodationId'], ['id'])
        batch_op.drop_column('accommodationType')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reviews_yandex_review_id', ['yandexReviewId'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_yandex_review_id', type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodationType', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_bookings_accommodation', type_='foreignkey')
        batch_op.drop_column('accommodationId')

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodations_id'))

    op.drop_table('accommodations')
    # ### end Alembic commands ###
