"""add_capacity_and_price_to_accommodations

Revision ID: 801d423df645
Revises: 27af621ff057
Create Date: 2026-05-05 12:44:14.840874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801d423df645'
down_revision: Union[str, Sequence[str], None] = '27af621ff057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pricePerNight', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_column('pricePerNight')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
