"""add_accommodation_images

Revision ID: bc0191b932f3
Revises: 551c70535658
Create Date: 2026-05-10 15:32:54.104553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0191b932f3'
down_revision: Union[str, Sequence[str], None] = '551c70535658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accommodationId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodationId'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_images_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_images_id'))

    op.drop_table('accommodation_images')
    # ### end Alembic commands ###
