"""add_phone_numbers_and_emails

Revision ID: bdd70b782cd4
Revises: 5a14d69947ad
Create Date: 2026-05-05 22:28:08.184915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd70b782cd4'
down_revision: Union[str, Sequence[str], None] = '5a14d69947ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_addresses_id'), ['id'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('isVisibleInHeader', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_id'), ['id'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yandexMapEmbed', sa.Text(), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('mapUrl')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('mapUrl', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('yandexMapEmbed')

    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_id'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('email_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_addresses_id'))

    op.drop_table('email_addresses')
    # ### end Alembic commands ###
