"""add_phone_numbers_and_emails

Revision ID: bdd70b782cd4
Revises: 5a14d69947ad
Create Date: 2026-05-05 22:28:08.184915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd70b782cd4'
down_revision: Union[str, Sequence[str], None] = '5a14d69947ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Таблицы телефонов/почты + yandexMapEmbed; перенос данных из старых колонок contacts."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    contact_col_names: set[str] = set()
    if inspector.has_table("contacts"):
        contact_col_names = {c["name"] for c in inspector.get_columns("contacts")}

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_addresses_id'), ['id'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('isVisibleInHeader', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_id'), ['id'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yandexMapEmbed', sa.Text(), nullable=True))

    # Перенос mapUrl → yandexMapEmbed, phone → phone_numbers, email → email_addresses
    is_sqlite = bind.dialect.name == "sqlite"
    now_sql = "datetime('now')" if is_sqlite else "CURRENT_TIMESTAMP"
    if "mapUrl" in contact_col_names:
        op.execute(
            sa.text(
                "UPDATE contacts SET yandexMapEmbed = mapUrl "
                "WHERE mapUrl IS NOT NULL AND TRIM(mapUrl) != ''"
            )
        )
    if "phone" in contact_col_names:
        op.execute(
            sa.text(
                f"INSERT INTO phone_numbers (number, isVisibleInHeader, sortOrder, createdAt, updatedAt) "
                f"SELECT phone, 1, 0, {now_sql}, {now_sql} FROM contacts "
                f"WHERE phone IS NOT NULL AND TRIM(phone) != ''"
            )
        )
    if "email" in contact_col_names:
        op.execute(
            sa.text(
                f"INSERT INTO email_addresses (email, sortOrder, createdAt, updatedAt) "
                f"SELECT email, 0, {now_sql}, {now_sql} FROM contacts "
                f"WHERE email IS NOT NULL AND TRIM(email) != ''"
            )
        )

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        if "phone" in contact_col_names:
            batch_op.drop_column("phone")
        if "mapUrl" in contact_col_names:
            batch_op.drop_column("mapUrl")
        if "email" in contact_col_names:
            batch_op.drop_column("email")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('mapUrl', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('yandexMapEmbed')

    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_id'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('email_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_addresses_id'))

    op.drop_table('email_addresses')
    # ### end Alembic commands ###
