"""add_email_and_booking_user

Revision ID: e19bc688c377
Revises: 801d423df645
Create Date: 2026-05-05 15:22:35.595325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19bc688c377'
down_revision: Union[str, Sequence[str], None] = '801d423df645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toEmail', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('bodyPreview', sa.Text(), nullable=True),
    sa.Column('templateType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('messageId', sa.String(length=500), nullable=True),
    sa.Column('sentAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_id'), ['id'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('bodyHtml', sa.Text(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_id'), ['id'], unique=False)

    op.create_table('smtp_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('useTls', sa.Boolean(), nullable=False),
    sa.Column('fromEmail', sa.String(length=320), nullable=True),
    sa.Column('fromName', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_userId_users', 'users', ['userId'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordHash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emailVerified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('emailVerified')
        batch_op.drop_column('passwordHash')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_userId_users', type_='foreignkey')
        batch_op.drop_column('userId')

    op.drop_table('smtp_settings')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_id'))

    op.drop_table('email_templates')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_id'))

    op.drop_table('email_logs')
    # ### end Alembic commands ###
